import type { SDKConfig } from "./src/types.js";

const sdks = {
  cli: {
    displayName: "CLI",
    icon: "terminal",
    order: 7,
    repo: "https://github.com/e2b-dev/e2b.git",
    tagPattern: "@e2b/cli@",
    tagFormat: "@e2b/cli@{version}",
    sdkPath: "packages/cli",
    generator: "cli",
    required: true,
    minVersion: "1.0.0",
  },

  "js-sdk": {
    displayName: "SDK (JavaScript)",
    icon: "square-js",
    order: 1,
    repo: "https://github.com/e2b-dev/e2b.git",
    tagPattern: "e2b@",
    tagFormat: "e2b@{version}",
    sdkPath: "packages/js-sdk",
    generator: "typedoc",
    required: true,
    minVersion: "1.0.0",
  },

  "python-sdk": {
    displayName: "SDK (Python)",
    icon: "python",
    order: 2,
    repo: "https://github.com/e2b-dev/e2b.git",
    tagPattern: "@e2b/python-sdk@",
    tagFormat: "@e2b/python-sdk@{version}",
    sdkPath: "packages/python-sdk",
    generator: "pydoc",
    required: true,
    minVersion: "1.0.0",
    basePackage: "e2b",
    fallbackPackages: [
      "e2b.sandbox_sync",
      "e2b.sandbox_async",
      "e2b.exceptions",
      "e2b.template",
      "e2b.template_sync",
      "e2b.template_async",
    ],
    submodules: {
      "e2b.template": ["logger", "readycmd"],
    },
  },

  "code-interpreter-js-sdk": {
    displayName: "Code Interpreter SDK (JavaScript)",
    icon: "square-js",
    order: 3,
    repo: "https://github.com/e2b-dev/code-interpreter.git",
    tagPattern: "@e2b/code-interpreter@",
    tagFormat: "@e2b/code-interpreter@{version}",
    sdkPaths: ["js"],
    generator: "typedoc",
    required: false,
    minVersion: "1.0.0",
  },

  "code-interpreter-python-sdk": {
    displayName: "Code Interpreter SDK (Python)",
    icon: "python",
    order: 4,
    repo: "https://github.com/e2b-dev/code-interpreter.git",
    tagPattern: "@e2b/code-interpreter-python@",
    tagFormat: "@e2b/code-interpreter-python@{version}",
    sdkPaths: ["python"],
    generator: "pydoc",
    required: false,
    minVersion: "1.0.0",
    basePackage: "e2b_code_interpreter",
    fallbackPackages: ["e2b_code_interpreter"],
  },

  "desktop-js-sdk": {
    displayName: "Desktop SDK (JavaScript)",
    icon: "square-js",
    order: 5,
    repo: "https://github.com/e2b-dev/desktop.git",
    tagPattern: "@e2b/desktop@",
    tagFormat: "@e2b/desktop@{version}",
    sdkPaths: ["packages/js-sdk"],
    generator: "typedoc",
    required: false,
    minVersion: "1.0.0",
  },

  "desktop-python-sdk": {
    displayName: "Desktop SDK (Python)",
    icon: "python",
    order: 6,
    repo: "https://github.com/e2b-dev/desktop.git",
    tagPattern: "@e2b/desktop-python@",
    tagFormat: "@e2b/desktop-python@{version}",
    sdkPaths: ["packages/python-sdk"],
    generator: "pydoc",
    required: false,
    minVersion: "1.0.0",
    basePackage: "e2b_desktop",
    fallbackPackages: ["e2b_desktop"],
  },
} as const satisfies Record<string, SDKConfig>;

export default sdks;
